### ISSUE TITLE
Disable Proxy for 'whitelisted' domains

### ISSUE THREAD

**Issue by jipvankuijk** [hunterirving/macproxy_plus#1]
Hey there,

It would be great if there is an extension, that allows a list of domains to not be altered by the proxy, beside maybe https>http. 

I have macintosh.jipvankuijk.com which already shows perfectly on older browsers, and via the proxy looks worse as an example.

Cheers.

**Comment by hunterirving** [comment]
Hey there, thanks for checking out the project.

What computer and browser are you using?
I've been using MacWeb 2.0, which doesn't have CSS support, so currently MPP strips all CSS from all pages.
This could be what's causing your site to look worse.
If it is just a CSS issue, the change should be fairly straightforward. Would a boolean flag in ```config.py``` that globally allows/disallows CSS stripping solve the issue for you?

Images of the expected rendering and the actual rendering might be helpful for debugging. And if your vintage browser has a way to view a page's source, before and after images of the HTML the browser is receiving might also be helpful.

**Comment by jipvankuijk** [comment]
Hey!

I'm using a Macintosh Plus, and Macintosh SE running System 7.0 both with MacWeb 2.1, these indeed don't support CSS and they work fine.

On my SE/30 however I can use Internet Explorer 3.1 or iCab 2.9.9. These browsers do support, in a limited fashion CSS and inline images etc.

I've already added a piece of code that adds CSS code inline for images to set the max width to 480 pixels, and reduced the image conversion script to match 480 width and 300 height.

But it would be nice to have a way to have a list in proxy.py or in an extension that can be used as a whitelist, where the proxy does not do anything to the html code, no css removal etc, and only run the image processing(if possible).

Maybe the flag to enable or disable CSS stripping would be a great start.

**Comment by hunterirving** [comment]
Hey @jipvankuijk,

I just [merged a PR](https://github.com/hunterirving/macproxy_plus/pull/6) that should address these issues.
As of a8e8d1acc56cb3d2a81a77518233c04c2b09cf4d, MacProxy Plus now allows you to specify a whitelist in config.py, which disables tag and attribute stripping for whitelisted domains.
Additionally, config.py now allows you to specify some image conversion settings (max_width, max_height, etc).

You can also quickly switch between presets for different browsers (stored in /presets) by specifying a PRESET string in config.py.

If this addresses your need, I'll close this issue.

Thanks again for your suggestion! I think it pushed the project in a good direction.

**Comment by hunterirving** [comment]
Closing this for now, as the requested feature has been implemented.
